#!/usr/bin/env bash
# Write env/deployment.auto.tfvars from resolve-deployment TF_VAR_* lines.
# CLI -var-file (later file) overrides prod.tfvars; TF_VAR_* alone does not.
set -euo pipefail

resolve_file="${1:?resolve output file required}"
outfile="${2:-env/deployment.auto.tfvars}"

if ! grep -q '^DEPLOYMENT_MODE=sandbox' "$resolve_file"; then
  rm -f "$outfile"
  exit 0
fi

{
  echo "# Generated by CI for workflow_dispatch slug deploys. Do not commit."
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      TF_VAR_*=*)
        key="${line#TF_VAR_}"
        key="${key%%=*}"
        val="${line#*=}"
        # HCL string escape: backslash and double-quote
        val="${val//\\/\\\\}"
        val="${val//\"/\\\"}"
        printf '%s = "%s"\n' "$key" "$val"
        ;;
    esac
  done < "$resolve_file"
} > "$outfile"

echo "Wrote $outfile ($(wc -l < "$outfile") lines)"
